### ISSUE TITLE
Issue following iOS SDK Setup Guide - Step 4, Swift Package Manager

### ISSUE THREAD

**Issue by simon-videoloft** [OneSignal/OneSignal-XCFramework#106]
Trying to follow the setup guide. When I try to add the SDK via Swift Packager Manager (V5.2.7), I get a 'Package Resolution Failed' pop-up, with a message saying 'Couldn't get the list of tags:'.

If I click the 'Add Anyway' button, I then don't get the options to add the different libraries shown in the guide.

Using Xcode 15.4.

**Comment by nan-li** [comment]
Hi @simon-videoloft thanks for reaching out. I am not able to reproduce this. 
I am seeing from search results some things you can try on your end. Start [here](https://stackoverflow.com/questions/69555397/package-resolution-failed-couldnt-get-the-list-of-tags) perhaps?

**Comment by simon-videoloft** [comment]
Thank-you. It seems the issue is caused by Sourcetree 4.2.9: [https://jira.atlassian.com/browse/SRCTREE-8176](https://jira.atlassian.com/browse/SRCTREE-8176)
