### ISSUE TITLE
building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by neha275** [OneSignal/OneSignal-XCFramework#26]
**error**:
In ~/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '~/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'

when occurred
Migrate project from intel process to M1Chip

**Pods Details**
platform :ios, '14.2'
pod 'OneSignal', '>= 3.2.1', '< 4.0'

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  #only copy below line
  pod 'OneSignal', '>= 3.2.1', '< 4.0'
end

**System info**
Mac mini M1 Chip
Mac OS 11.6
Xcode 13

**What I tried** 

- Pods framework 
- setting the BuildActiveArchitectureOnly to Yes in the cocoapods project
- Excluded Architecture arm64 for iOS simulator
- Delete Derived Data and reinstall pods

**Comment by emawby** [comment]
@neha275 Hello this repository is for Swift Package Manager, but it looks like you are having trouble with Cocoapods. I am going to close this issue, please move this issue to the[ OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK)
