### ISSUE TITLE
Lib causing "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."

### ISSUE THREAD

**Issue by sidneivl** [OneSignal/OneSignal-XCFramework#27]
Hi,

I'm facing a problem when I add a XCFramework and try to send to test flight I get the error.

ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."

I removed the lib and the build occurred normally.

So, in my project I'm just using SPM and some Fats libs with a script to remove archs that are not used in the build.

To build the project I replaced the XCFramework for the OneSignal-iOS-SDK and is running well even using xcode 13.

**Comment by emawby** [comment]
@sidneivl Thank you for reporting. Which version did you experience this issue on?

**Comment by jkasten2** [comment]
Closing due to no reply.
