### ISSUE TITLE
invalid custom path 'OneSignalExtensionWrapper' for target 'OneSignalExtensionWrapper'

### ISSUE THREAD

**Issue by AndrewSB** [OneSignal/OneSignal-XCFramework#37]
after updating to the latest release, i get this error message

i've tried resetting package caches, restarting, etc.

any pointers?

**Comment by emawby** [comment]
@AndrewSB This is a bug in the repo I am working on a fix asap! In the meantime you should be able to use OneSignal-iOS-SDK instead of OneSignal-XCFramework. Those swift packages are now identical, but that repo doesn't have this issue

**Comment by emawby** [comment]
@AndrewSB The issue should be resolved on this repo now!
