### ISSUE TITLE
SwiftPM Package Resolution Failed (invalid checksums)

### ISSUE THREAD

**Issue by therealmyluckyday** [OneSignal/OneSignal-XCFramework#45]
Since v3.11.4 the checksums are invalid for all artifacts.
![Screenshot 2022-10-31 at 12 16 21](https://user-images.githubusercontent.com/32668175/198995839-e2be6ef0-87a3-42e2-9602-a67c2d02e1ab.png)

**Comment by nan-li** [comment]
Hi @therealmyluckyday, 

Have you tried again? This should be fixed, can you show the entire checksum error message, the parts that say "does not match xyz"?

**Comment by therealmyluckyday** [comment]
I'm was on 3.11.3, I can see it in the list of Package Dependencies:
![Screenshot 2022-11-02 at 10 04 17](https://user-images.githubusercontent.com/32668175/199448471-05431eb9-c1d8-4a4a-aa8c-2b0894617f13.png)
![Screenshot 2022-11-02 at 10 04 30](https://user-images.githubusercontent.com/32668175/199448521-b4e41a08-46be-46ae-8072-4ce6c3ed50a6.png)

I force the update to 3.11.4, the dependency disappears from the list. I try to build, I get checksum errors:
![Screenshot 2022-11-02 at 10 06 06](https://user-images.githubusercontent.com/32668175/199448906-3bf50848-8b86-449b-8ab2-dc19d6f25ee0.png)

I remove the dependency and add it back using up to next major versioning (3.0.0 < 4.0.0) and Package Resolution Failed:
![Screenshot 2022-11-02 at 10 07 41](https://user-images.githubusercontent.com/32668175/199449274-958f6227-7d08-4cd4-a416-c2785b013f21.png)

**Comment by guidev** [comment]
same

**Comment by BrandonBatt3** [comment]
same, xCode 14.0.1
