### ISSUE TITLE
Readme link to iOS reference docs is 404

### ISSUE THREAD

**Issue by JetForMe** [OneSignal/OneSignal-XCFramework#68]
The readme has a link to https://documentation.onesignal.com/docs/ios-native-sdk, which is 404

**Comment by jfishman1** [comment]
Thanks for reporting! I believe this is trying to direct to our mobile SDK docs: https://documentation.onesignal.com/docs/mobile-sdk

But it might try to point to our iOS Setup doc: https://documentation.onesignal.com/docs/ios-sdk-setup

Will setup a redirect. Thanks again for reporting!
